### PR TITLE
Make JSONSerialization.makeJSON public

### LINKED ISSUE #185: Parse - [NSObject: AnyObject]
Hello,

I am facing a problem about the Freddy Json Parser. I would like to parse a JSON response from the `didReceiveRemoteNotification` function.

I cannot parse directly the userInfo response.

```
func application(application: UIApplication, didReceiveRemoteNotification userInfo: [NSObject : AnyObject]) {
   let json = JSON(userInfo)
  }
```

Have yo any ideas?
Thank you. :-)

### PR DESCRIPTION
**Pull request by radex**
Fixes #185.

### CODE REVIEW

**Comment by radex** [comment]
Any chance of merging this? Important for my use case :(

**Comment by mdmathias** [comment]
I'm fine with making `makeJSON(with:)` public. 

@zwaldowski @jgallagher Any complaints?

@radex In the meantime, would you mind updating this branch with the latest from master so that we can merge the PR?

**Comment by radex** [comment]
@mdmathias done!

**Comment by mdmathias** [comment]
Excellent. Thanks @radex!

**Comment by radex** [comment]
Thank you!

**Pull request merged**
