### PR TITLE
Adding NotConvertableBecomesNil to Subscripting options

### PR DESCRIPTION
**Pull request by soheilbm**
Consider that the api responses changes the return value from one format to another. I know that server responses should not change the value type, but if it ever get change shouldn't just make the value to nil instead of failing? Thus, I would like to make this pull request to giving an option if the server return different value, it return nil type.

### CODE REVIEW

**Comment by jgallagher** [comment]
I'm not sure this should be part of Freddy directly; data type mismatch errors seem more serious than trying to wrangle `null` or missing keys. I guess I mean if you can handle an error of that magnitude (by assuming the value is `nil`), could this be accomplished by using `try?` at the call site?

**Comment by soheilbm** [comment]
Let's say I have a model like below:

    final public class ListingDetail: NSObject, JSONDecodable {
        public let statusCode: Int?
        public let price: Double?
        
     public required init(json: JSON) throws {
       statusCode = try json.int("data","data","statusCode", alongPath: [.MissingKeyBecomesNil, .NullBecomesNil])
       price  = try json.double("data","price",alongPath: [.MissingKeyBecomesNil, .NullBecomesNil])
     }
    }


So if my json has a statusCode but with string value the whole model get to failed. And in this situation I can't use 'try?' because i'm using 'let' inside my model. With this model if the value is not convertible, the model actually get EXC_BAD_ACCESS error. 

I thought maybe it would be a great if I could satisfy the Freddy if the value i'm looking for is not exactly the same type, then just return nil value instead.

**Comment by jgallagher** [comment]
Two questions for you:

* Can you explain what you mean by "I can't use `try?` because I'm using `let` inside my model"? Since your properties are optionals, that should work fine.
* Where are you getting an `EXC_BAD_ACCESS`? That shouldn't be happening from the code you've posted, unless you're `try!`-ing the model creation somewhere else.

**Comment by jgallagher** [comment]
Closing for now - if this is still an issue please re-open. Thanks!

**Pull request closed without merging**
